### ISSUE TITLE
Create a new data ribbon (on the bottom row)

### ISSUE THREAD

**Issue by huskerbsg** [j50n/blackholesuns#28]
Why:  Part of the appeal of the DARC is the dramatic effect it has on journeys versus traditional warping.  In the interest of showcasing the power of the tool in a statistical context, it would be helpful to display the actual hyperjump savings in an easy to read way.

What:  Create a new "data ribbon" on the bottom row with the following:
1.  Distance to Target in traditional hyperjumps (total LY distance divided by hyperjump capacity)
2. Number of Jumps required (based on using black holes and hyperjumps outlined in the route below)
3. Hyperjump reduction (in integer form and Percentage)
4. "Cornell Index" - number of black holes required for trip  

I've attached a small sample from the legacy DARC as an example
![sample summary](https://user-images.githubusercontent.com/50179988/57034203-ecd86700-6c1c-11e9-8806-e06e35c1faae.PNG)

**Comment by huskerbsg** [comment]
the screenshot sample doesn't include a sample of the "jump reduction percentage", but that is one of the indexes that I'd like to see included

**Comment by j50n** [comment]
Calling it done. Lots of live feedback tweaked the final product a bit, but looks good to me!
