### ISSUE TITLE
Map gets pushed out of position on Firefox

### ISSUE THREAD

**Issue by huskerbsg** [j50n/blackholesuns#29]
The map gets pushed below the Time and Fuel radio buttons on Firefox from time to time.

![ffxmap](https://user-images.githubusercontent.com/50179988/57321250-f35c5800-70ce-11e9-89cf-43758a5ce90f.PNG)

**Comment by j50n** [comment]
Closing as won't do, for now. This is pure-css responsive behavior. When we move to bootstrap, this is likely to change. As we redesign the layout with a different settings page, it will definitely change.
